name: "Main"
on:
  push:
    branches:
      - "master"
      - "main"
      - "v[0-9]+.[0-9]+.[0-9]+"

    paths-ignore:
      - "README.md"

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build test
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose build
